version: "3.8"
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: ai_planet
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgpass
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./backend
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  db_data:
